name: Set Scaleway Bucket CORS
on: [workflow_dispatch]

jobs:
  update-cors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Apply CORS configuration
        working-directory: .scaleway
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.SCW_REGION }}
          S3_BUCKET: ${{ secrets.APP_S3_BUCKET }}
          S3_ENDPOINT: ${{ secrets.APP_S3_ENDPOINT }}
          PUBLIC_APP_URL: ${{ vars.PUBLIC_APP_URL }}
        run: |
          export PUBLIC_APP_URL
          envsubst < template-bucket-cors.json > cors.json
          aws s3api put-bucket-cors \
            --bucket "$S3_BUCKET" \
            --cors-configuration file://cors.json \
            --endpoint-url "$S3_ENDPOINT"
